apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: notes-service-hpa
spec:
    maxReplicas: 9
    minReplicas: 2
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: notes-service
    targetCPUUtilizationPercentage: 50
