apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-role-binding
#  namespace: dev
subjects:
  - kind: ServiceAccount
    name: dev-user

roleRef:
  kind: Role
  name: dev-role
  apiGroup: rbac.authorization.k8s.io